### ISSUE TITLE
Getting constant Kernel::Settings not defined error at start

### ISSUE THREAD

**Issue by mico** [rs-pro/rails_admin_settings#9]
I'm using rails 3.2.19 and when I starting application or trying to run migration, I getting an error:
```
$ rails c
/Users/mico/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rails_config-0.3.3/lib/rails_config.rb:36:in `remove_const': constant Kernel::Settings not defined (NameError)
	from /Users/mico/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rails_config-0.3.3/lib/rails_config.rb:36:in `load_and_set_settings'
	from /Users/mico/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/rails_config-0.3.3/lib/rails_config/integration/rails.rb:15:in `block in <class:Railtie>'
	from /Users/mico/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/mico/.rbenv/versions/2.1.7/lib/ruby/gems/2.1.0/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
```

**Comment by glebtv** [comment]
rails_config gem is not this gem )
https://github.com/railsconfig/config

**Comment by dostapn** [comment]
and?
